const annoyQuestions = {
    en: [
        "Weird talent",
        "Hobby",
        "Favourite memory",
        "Secret",
        "Hidden talent",
        "Embarrassing moment",
        "First impression",
        "Mood",
        "Guilty pleasure",
        "Crush",
        "Weird habit",
        "Random fact",
        "Secret wish",
        "Night thoughts",
        "Funny dream"
    ],
    es: [
        "Talento raro",
        "Pasatiempo",
        "Recuerdo favorito",
        "Secreto",
        "Talento oculto",
        "Momento vergonzoso",
        "Primera impresión",
        "Estado de ánimo",
        "Placer culposo",
        "Crush",
        "Hábito raro",
        "Dato aleatorio",
        "Deseo secreto",
        "Pensamientos nocturnos",
        "Sueño divertido"
    ],
    hi: [
        "अजीब टैलेंट",
        "शौक",
        "पसंदीदा याद",
        "राज़",
        "छुपा हुआ टैलेंट",
        "शर्मनाक पल",
        "पहला इंप्रेशन",
        "मूड",
        "गिल्टी प्लेजर",
        "क्रश",
        "अजीब आदत",
        "रैंडम फैक्ट",
        "सीक्रेट विश",
        "रात के ख्याल",
        "मजेदार सपना"
    ],
    ta: [
        "விசித்திர திறமை",
        "விருப்பம்",
        "பிடித்த நினைவு",
        "ரகசியம்",
        "மறைந்த திறமை",
        "வெட்கப்படத்தக்க தருணம்",
        "முதல் பார்வை",
        "மனநிலை",
        "குற்ற உணர்ச்சி மகிழ்ச்சி",
        "க்ரஷ்",
        "விசித்திர பழக்கம்",
        "சீரற்ற தகவல்",
        "ரகசிய ஆசை",
        "இரவு எண்ணங்கள்",
        "வேடிக்கையான கனவு"
    ],
    mr: [
        "विचित्र टॅलेंट",
        "छंद",
        "आवडती आठवण",
        "गुपित",
        "लपलेला टॅलेंट",
        "लाजिरवाणा क्षण",
        "पहिली छाप",
        "मूड",
        "गिल्टी प्लेझर",
        "क्रश",
        "विचित्र सवय",
        "रँडम तथ्य",
        "गुपित इच्छा",
        "रात्रीचे विचार",
        "मजेदार स्वप्न"
    ],
    enhi: [
        "Ajeeb Talent",
        "Shauk",
        "Favourite Yaad",
        "Raaz",
        "Hidden Talent",
        "Embarrassing Moment",
        "First Impression",
        "Mood",
        "Guilty Pleasure",
        "Crush",
        "Weird Habit",
        "Random Fact",
        "Secret Wish",
        "Night Thoughts",
        "Funny Dream"
    ]
};

module.exports = annoyQuestions;